# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake.exe

# The command to remove a file.
RM = /usr/bin/cmake.exe -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /d/Personal/Desktop/multi_dev_library/foxlibc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /d/Personal/Desktop/multi_dev_library/foxlibc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake.exe --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake.exe -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /d/Personal/Desktop/multi_dev_library/foxlibc/CMakeFiles /d/Personal/Desktop/multi_dev_library/foxlibc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /d/Personal/Desktop/multi_dev_library/foxlibc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named foxlibc

# Build rule for target.
foxlibc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 foxlibc
.PHONY : foxlibc

# fast build rule for target.
foxlibc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/build
.PHONY : foxlibc/fast

linkedlist.o: linkedlist.c.o
.PHONY : linkedlist.o

# target to build an object file
linkedlist.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/linkedlist.c.o
.PHONY : linkedlist.c.o

linkedlist.i: linkedlist.c.i
.PHONY : linkedlist.i

# target to preprocess a source file
linkedlist.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/linkedlist.c.i
.PHONY : linkedlist.c.i

linkedlist.s: linkedlist.c.s
.PHONY : linkedlist.s

# target to generate assembly for a file
linkedlist.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/linkedlist.c.s
.PHONY : linkedlist.c.s

main.o: main.c.o
.PHONY : main.o

# target to build an object file
main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/main.c.o
.PHONY : main.c.o

main.i: main.c.i
.PHONY : main.i

# target to preprocess a source file
main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/main.c.i
.PHONY : main.c.i

main.s: main.c.s
.PHONY : main.s

# target to generate assembly for a file
main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/main.c.s
.PHONY : main.c.s

stack_link.o: stack_link.c.o
.PHONY : stack_link.o

# target to build an object file
stack_link.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/stack_link.c.o
.PHONY : stack_link.c.o

stack_link.i: stack_link.c.i
.PHONY : stack_link.i

# target to preprocess a source file
stack_link.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/stack_link.c.i
.PHONY : stack_link.c.i

stack_link.s: stack_link.c.s
.PHONY : stack_link.s

# target to generate assembly for a file
stack_link.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/stack_link.c.s
.PHONY : stack_link.c.s

string.o: string.c.o
.PHONY : string.o

# target to build an object file
string.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/string.c.o
.PHONY : string.c.o

string.i: string.c.i
.PHONY : string.i

# target to preprocess a source file
string.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/string.c.i
.PHONY : string.c.i

string.s: string.c.s
.PHONY : string.s

# target to generate assembly for a file
string.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/foxlibc.dir/build.make CMakeFiles/foxlibc.dir/string.c.s
.PHONY : string.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... foxlibc"
	@echo "... linkedlist.o"
	@echo "... linkedlist.i"
	@echo "... linkedlist.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... stack_link.o"
	@echo "... stack_link.i"
	@echo "... stack_link.s"
	@echo "... string.o"
	@echo "... string.i"
	@echo "... string.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

